sudo: required
dist: trusty

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

notifications:
  email: false

before_install:
  - echo `pwd`
  - lsb_release -a
  - sudo apt-get update
  - cd $HOME
  - git clone https://github.com/OpenKinect/libfreenect2.git
  - cd libfreenect2/depends
  - ./download_debs_trusty.sh
  - sudo apt-get install -y build-essential cmake pkg-config
  - sudo dpkg -i debs/libusb*deb
  - sudo apt-get install -y libturbojpeg libjpeg-turbo8-dev
  - sudo apt-get install -y libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev
  - sudo dpkg -i debs/libglfw3*deb
  - sudo apt-get install -f
  - sudo apt-get install -y libgl1-mesa-dri-lts-vivid
  - cd $HOME/libfreenect2
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - if [["$TRAVIS_PYTHON_VERSION" == "2.7"]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda config --add channels pypi
  - conda info -a
  - deps='numpy cython'
  - conda create -q -n test-environment "python=$TRAVIS_PYTHON_VERSION" $deps
  - source activate test-environment
  - cd $TRAVIS_BUILD_DIR

script:
  - pip install -e .
